name: CI/CD Pipeline with MongoDB

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test  # Si tienes pruebas configuradas

      - name: Build Docker image
        run: docker build -t my-app:latest .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login to AWS EC2
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region us-east-1

      - name: Deploy to AWS EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_IP }} << EOF
            docker stop app || true
            docker rm app || true
            docker pull my-app:latest
            docker run -d -p 80:3200 \
              --name app \
              -e MONGODB_URI=${{ secrets.MONGODB_URI }} \
              my-app:latest
          EOF
